PYTHON=python

.PHONY:test
test: run

.PHONY:run
run: run_ex1 run_ex2 run_ex3 run_ex4 run_ex5 run_ex6

.PHONY:run_ex1
run_ex1:
	${PYTHON} ex1.py ${SLEPC_OPTIONS}

.PHONY:run_ex2
run_ex2:
	${PYTHON} ex2.py ${SLEPC_OPTIONS}

.PHONY:run_ex3
run_ex3:
	${PYTHON} ex3.py ${SLEPC_OPTIONS}
.PHONY:run_ex4
run_ex4:
	${PYTHON} ex4.py ${SLEPC_OPTIONS}

.PHONY:run_ex5
run_ex5:
	${PYTHON} ex5.py ${SLEPC_OPTIONS}

.PHONY:run_ex6
run_ex6:
	${PYTHON} ex6.py ${SLEPC_OPTIONS}
