PYTHON=python

.PHONY:test
test: run

.PHONY:run
run: run_ex1 run_ex2 run_ex3 run_ex4 run_ex5 run_ex6 run_ex7 run_ex8 run_ex9 run_ex10 run_ex11

.PHONY:run_ex1
run_ex1:
	${PYTHON} ex1.py ${SLEPC_OPTIONS}

.PHONY:run_ex2
run_ex2:
	${PYTHON} ex2.py ${SLEPC_OPTIONS}

.PHONY:run_ex3
run_ex3:
	${PYTHON} ex3.py ${SLEPC_OPTIONS}
.PHONY:run_ex4
run_ex4:
	${PYTHON} ex4.py ${SLEPC_OPTIONS}

.PHONY:run_ex5
run_ex5:
	${PYTHON} ex5.py ${SLEPC_OPTIONS}

.PHONY:run_ex6
run_ex6:
	${PYTHON} ex6.py ${SLEPC_OPTIONS}

.PHONY:run_ex7
run_ex7:
	${PYTHON} ex7.py ${SLEPC_OPTIONS}

.PHONY:run_ex8
run_ex8:
	${PYTHON} ex8.py ${SLEPC_OPTIONS}

.PHONY:run_ex9
run_ex9:
	${PYTHON} ex9.py ${SLEPC_OPTIONS}

.PHONY:run_ex10
run_ex10:
	${PYTHON} ex10.py ${SLEPC_OPTIONS}

.PHONY:run_ex11
run_ex11:
	${PYTHON} ex11.py ${SLEPC_OPTIONS}
